name: Node.js CI

on:
  pull_request:
    branch: main

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
      
    steps:
      - name: Run tests
        run: npm test

      